# #####################################################
# General CGI configurations
# #####################################################
#
# Exports:
# $ON ...
# $MAX_PROC_POOL
# $PROC_CREATION
# $BASE_PROC_SETUP
# 
# #####################################################


# Switch button
$ON = $true


# Max number of processes generated by the CGI app
$MAX_PROC_POOL = 20


# #####################################################
# General Process Configurations
# #####################################################


# Parameters for creating the System.Diagnostics.Process object
$PROC_CREATION = @{
		PARAM01 = "";
		PARAM02 = "";
		PARAM03 = ""
	}


# Setups for the System.Diagnostics.Process object
$BASE_PROC_SETUP = @{
		PARAM01 = "";
		PARAM02 = "";
		PARAM03 = ""
	}

